### ISSUE TITLE
Streamable link not working

### ISSUE THREAD

**Issue by maloros12** [Fuguu/videoBackground#2]
i click settings in the plugin menu, put in the link to my streamable upload: https://streamable.com/7l409b thenw nothing happens...

**Comment by Fuguu** [comment]
https://github.com/Fuguu/videoBackground#getting-direct-link
it has seems that streamable has removed the ability to download videos so getting the link requires a bit of messing around but for all links, that is not youtube, will need to be a direct link to the mp4/WebM
